### ISSUE TITLE
Multiple DNS Provider Support

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/multicluster-gateway-controller#189]
Add support for multiple DNS providers.

Currently we only support route53 as a dns provider, but many potential users of this project and eventual product might already be using one of the many other providers for their DNS management.

MCG currently has three features of any DNS provider that we require in order to offer full support,  DNSRecord management, Zone management  and DNS Health checks. We do not however want to limit to providers that only offer this functionality, so to add support for a provider the minimum that provider should offer is API access to managed DNS records. 
  
Support will be added for aws(route53), google(gcloud DNS), Azure and investigation into possible adding CoreDNS (intended for local dev purposes), with the following proposed initial support:

| Provider  | DNS Records | DNS Zones | DNS Health |
| ------------- | ------------- |  ------------- | ------------- |
| AWS Route 53 | X | X | X |
| Google Cloud DNS  | X | X | ? |
| AzureDNS| X | X | ? |
| CoreDNS| X | - | - |

- [x] #220
- [x] #228
- [x] #258
- [ ] https://github.com/Kuadrant/kuadrant-dns-operator/issues/12
- [ ] Add CoreDNS provider (Default for local development)
- [ ] Update docs with currently supported matrix and tutorials for each supported provider

**Comment by philbrookes** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by philbrookes** [comment]
This issue is stale because it has been open for 60 days with no activity.

**Comment by philbrookes** [comment]
This issue is stale because it has been open for 60 days with no activity.

**Comment by philbrookes** [comment]
This issue was closed because it has been inactive for 30 days since being marked as stale.
