### ISSUE TITLE
Kuadrant.io Refresh

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/multicluster-gateway-controller#205]
Update https://kuadrant.io/ to reflect the latest work going on in the Kuadrant space.
In general, tasks align with the [MVP](https://github.com/Kuadrant/multicluster-gateway-controller/issues?q=is%3Aissue+is%3Aopen+label%3Amvp) set of issues

*Tasks*

* [x] #278
* [x] #279
* [x] #280
* [x]  https://github.com/Kuadrant/kuadrant.github.io/issues/19
* [ ] Using Kuadrant Data Plane APIs with mgc
* [x] #285
* [ ] How to place a Gateway - depends on #74 
* [ ] How to configure a DNS Policy - depends on #137 
* [x] How to use ManagedZone API - depends on #202 
* [ ] Create an introduction video highlighting key use cases and an architectural overview
* [ ] Example of using mgc with skupper - depends on #204 
* [ ] Example of using mgc with submariner - depends on #164 
* [ ] How to configure different certificate authorities - depends on #203 
* [ ] How to configure different DNS providers - depends on #189
