### ISSUE TITLE
Implement TLSPolicy

### ISSUE THREAD

**Issue by jasonmadigan** [Kuadrant/multicluster-gateway-controller#374]
**What**

Move all TLS logic into a new TLSPolicy controller, with distinct reconciliation.

Currently, the gateway controller reconciliation will create and update TLS certificates. The proposed TLSPolicy targets a Gateway and its reconciliation will ensure certificates are in place for a given Gateway. This is more in line with our newly adopted DNSPolicy, which manages all DNS resources for a target Gateway.

**How**

- [x] #378
- [x] Look to relocate & re-use `cluster_eventmapper.go` & `gateway_eventmapper.go`, as they'll be useful for TLSPolicy as well.
- [x] Remove old certificate management from the existing gateway controller (e.g. `reconcileTLS`)
- [ ] Relocate certificate management services/structs that exist in the gateway controller, to the new TLSPolicy controller (e.g. `CertificateService`)
- [x] Handle upstream Gateway removal and cleanup of associated resources (e.g. `Certificates.CleanupCertificates`)
- [ ] For now, create a default TLSPolicy if none exist, with a default issuer (see `glbc-ca` default, self-signed issuer currently). Note: This could do with some discussion as to how this is created - this is mostly useful for devs, although it also has some usefulness for those users who are getting started with Kuadrant. It may be more appropriate to create this via our setup scripts outside of the running process.
- [x] TLSPolicy will use a similar policy attachment pattern as other resources such as R`ateLimitPolicy`, `AuthPolicy` and `DNSPolicy`.
- [x] A standalone description document for TLSPolicy should be created, similar to https://github.com/Kuadrant/multicluster-gateway-controller/pull/373
- [x] If we choose to not-create TLSPolicy by default, we should alter the steps present in the OCM setup walkthrough to create a working default self-signed issuer.
- [x] Kuadrant policies retain an annotation on targetted Gateways, which will be useful to build lists of "managed" Gateways

At a high level, reconciliation should cover:
- [x] TLSPolicy creation. Triggers reconcile, create certificates & keys for Gateway listeners, similar to how these are created currently (but now centralised in the TLSPolicy controller).
- [x] Gateway deletion - triggers reconcile and delete associated resources owned by TLSPolicy (certificates and secrets).
- [x] TLSPolicy deletion: deletes resources owned by TLSPolicy. Remove TLSPolicy annotation from targetted Gateways.
- [x] TLSPolicy target ref change - cleanup existing resources, recreate afresh for new target gateway next loop.
- [x] Appropriate TLSPolicy status
- [x] Changes + new tests

**Comment by jasonmadigan** [comment]
cc @maleck13 @mikenairn @david-martin

**Comment by david-martin** [comment]
> * create a default TLSPolicy if none exist, with a default issuer

Agreed that It may be more appropriate to create this via our setup scripts outside of the running process.

**Comment by david-martin** [comment]
> * Gateway deletion - triggers reconcile and delete associated resources owned by TLSPolicy (certificates and secrets).
> * [ ]  TLSPolicy deletion: deletes resources owned by TLSPolicy. Remove TLSPolicy annotation from targetted Gateways.

ownerReferences would be a standard way to handle deletion of Certificates and Secrets when a TLSPolicy is deleted.

Deletion of a Gateway shouldn't delete a TLSPolicy, but should probably trigger delete of any Certificates and Secrets that are no longer referenced in that Gateway, but were originally created by the TLSPolicy.

**Comment by jasonmadigan** [comment]
> > * Gateway deletion - triggers reconcile and delete associated resources owned by TLSPolicy (certificates and secrets).
> > * [ ]   TLSPolicy deletion: deletes resources owned by TLSPolicy. Remove TLSPolicy annotation from targetted Gateways.
> 
> ownerReferences would be a standard way to handle deletion of Certificates and Secrets when a TLSPolicy is deleted.
> 
> Deletion of a Gateway shouldn't delete a TLSPolicy, but should probably trigger delete of any Certificates and Secrets that are no longer referenced in that Gateway, but were originally created by the TLSPolicy.

Yeah, sorry - re: cleanup, what you had in mind is what I had in mind. Cleanup of references that are no longer valid is probably a more accurate description.

**Comment by jasonmadigan** [comment]
> > * Appropriate TLSPolicy status
> 
> Thoughts on status conditions?
> 
> I'm thinking at the very least 1 condition type, `Ready`. e.g.
> 
> ```yaml
>   - type: Ready
>     status: True
>     message: "TLSPolicy valid and ready for certification management"
>     reason: Valid
> ```
> 
> ```yaml
>   - type: Ready
>     status: False
>     message: "Issuer not found"
>     reason: Invalid
> ```
> 
> ```yaml
>   - type: Ready
>     status: False
>     message: "TargetRef not found"
>     reason: Invalid
> ```

These look good. Given we're inlining certman.Certificate I wonder if we should consider inlining some of its status blocks as well?

e.g. https://github.com/cert-manager/cert-manager/blob/615422b5bf59cb60931fefc9f0787231b894b1fd/internal/controller/certificates/policies/checks.go#L43

**Comment by david-martin** [comment]
> Given we're inlining certman.Certificate I wonder if we should consider inlining some of its status blocks as well?

Do you mean proxy back the Certificate status block in the TLSPolicy status block?
A TLSPolicy would related to 0 or more Certificates, so we'd have similar problems to [gateway status aggregation](https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/proposals/status-aggregation.md) in the hub.

I'm wondering now what validation the tlspolicy controller would do ahead of creating any Certificates,
vs. making the Certificates status available either on the TLSPolicy status or by rbac on the Certificates themselves.
If we start to validate the Certificate fields in the TLSPolicy, that is duplicating logic presumably already in cert-manager.

I'm thinking the following might be reasonable:

- Don't validate the Certificate fields in the TLSPolicy beyond what the CRD validation provides (e.g. min/max length, regex etc..). If all that checks out, the TLSPolicy is `Ready`
- If there's a problem with 1 or more Certficates as represented on the [status](https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateStatus) (e.g. not `Ready`), aggregate that back to the TLSPolicy as a different status condition e.g. `CertificatesReady`.
- If all certificate statuses are `Ready`, then `CertificatesReady` on the TLSPolicy is true. If 1 or more Certificates are not `Ready`, then `CertificatesReady` on the TLSPolicy is false.
- The message for that `CertificatesReady` status condition on the TLSPolicy can be a list of Certificates that are not `Ready`.  For further details, the individual Certificate status can be looked up directly on the Certificate resource if desired by the user.

**Comment by mikenairn** [comment]
All of the points in this are covered by https://github.com/Kuadrant/multicluster-gateway-controller/pull/402

**Comment by jasonmadigan** [comment]
@mikenairn agree, we can probably mark this as closed via #402

**Comment by mikenairn** [comment]
Resolved by https://github.com/Kuadrant/multicluster-gateway-controller/pull/402
