### ISSUE TITLE
Improvements to user experience flow and getting started (docs, website, setup etc)

### ISSUE THREAD

**Issue by laurafitzgerald** [Kuadrant/multicluster-gateway-controller#403]
This issue (epic) captures a number of issues in order to ensure that the user first experience is well documented.

As a follow on to the [current](https://docs.kuadrant.io/multicluster-gateway-controller/docs/getting-started/) getting started script and document done as part of https://github.com/Kuadrant/multicluster-gateway-controller/issues/286 we want to refine the follow on steps that a user can follow. 

Note: documents are sourced from their respective repos, hence documents for MGC should be updated inside the MGC repo docs folder. Any sources to old documents that we decide to not include should be removed from the navigation and as such removed from the website. Current set of docs that are sourced from MGC repo are listed here https://github.com/Kuadrant/docs.kuadrant.io/blob/main/mkdocs.yml#L134-L149

- [x] document about defining and distribute a gateway
- [x] document about define and create [DNSPolicy](https://github.com/Kuadrant/multicluster-gateway-controller/issues/478) and TLS policy
- [ ] document about deploying an application into multiple clusters using argocd leveraging a HTTRoute viea your new gateways. 
- [x] document about protect your new HTTPRoute with rate limits and Auth
- [x] #404 
- [x] #300 
- [x] #454 
- [x] #475 
- [x] #476

Overall Layout suggestion 
- policies:
  - DNSPolicy 
  - RateLimitPolicy
  - AuthPolicy
  - TLSPolicy
- Installation:
   - Multi-Cluster installation
   - Spoke service protection installation
