### ISSUE TITLE
Gateway Definition, Placement and Configuration

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#505]
**What** 

**Optional:** Follow the [quick start](https://docs.kuadrant.io/multicluster-gateway-controller/docs/getting-started/) to get an environment up and running.

Any bugs should be created in the MGC project and reference this issue and how to reproduce. Do not close this issue if there are outstanding bugs.

With an environment consisting of an OCM hub and spoke cluster, 

- [ ] Create a ManagedClusterSet resource that selects at least 1 ManagedCluster
- [ ] Bind that ManagedClusterSet to a given namespace
- [ ] Create a placement resource that specifies at least 1 cluster
- [ ] Create a Gateway in the same ns as your placement and label it with `cluster.open-cluster-management.io/placement: [placement name]`
- [ ] Check that the gateway is instantiated on your spoke cluster and the spec and status are as expected
- [ ] Check the hub gateway status reports the gateway as programmed and accepted with no error message
- [ ] Update the Hub Gateway with a new wildcard listener validate spec on spoke updated
- [ ] Update the Hub Gateway with a non wildcard listener validate spec on spoke updated
- [ ] Remove the new listeners from the Gateway in the hub, validate spec on spoke updated
- [ ] Define a HTTPS listener with a secret that doesn't exist, validate that the gateway is no longer in a programmed status state (waiting on #509 )
- [ ] Remove the placement and ensure the gateway is deleted (waiting on #420 and #583 )
- [ ] Change the placement to no longer select a clusterset or change the number of clusters to 0 Ensure the gateway is removed from the spoke cluster
- [ ] Label the gateway with a none existent placement and ensure it is clear what the issue is in the status of control plane

**Example Resouces**
```
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: gateway-clusters
spec:
  clusterSelector:
    labelSelector: 
      matchLabels:
        ingress-cluster: "true"
    selectorType: LabelSelector
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: gateway-clusters
  namespace: multi-cluster-gateways
spec:
  clusterSet: gateway-clusters
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: http-gateway
  namespace: multi-cluster-gateways
spec:
  numberOfClusters: 1
  clusterSets:
    - gateway-clusters
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: prod-web
  namespace: multi-cluster-gateways
  labels:
    cluster.open-cluster-management.io/placement: http-gateway
spec:
  gatewayClassName: kuadrant-multi-cluster-gateway-instance-per-cluster
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: specific
    hostname: 'specific.cb.hcpapps.net'
    port: 443
    protocol: HTTP
```

**Comment by maleck13** [comment]
There are some issues highlighted in https://github.com/Kuadrant/multicluster-gateway-controller/issues/420 that will cause this test case to fail currently.

**Comment by R-Lawton** [comment]
release-0.1.0-rc1

- [ ] Create a ManagedClusterSet resource that selects at least 1 ManagedCluster
- [ ] Bind that ManagedClusterSet to a given namespace
- [ ] Create a placement resource that specifies at least 1 cluster
- [ ] Create a Gateway in the same ns as your placement and label it with `cluster.open-cluster-management.io/placement: [placement name]`
- [ ] Check that the gateway is instantiated on your spoke cluster and the spec and status are as expected
- [ ] Check the hub gateway status reports the gateway as programmed and accepted with no error message
- [ ] Update the Hub Gateway with a new wildcard listener validate spec on spoke updated
- [ ] Update the Hub Gateway with a non wildcard listener validate spec on spoke updated
- [ ] Remove the new listeners from the Gateway in the hub, validate spec on spoke updated
- [ ] Define a HTTPS listener with a secret that doesn't exist, validate that the gateway is no longer in a programmed status state (waiting on #509 )
- [ ] Remove the placement and ensure the gateway is deleted (waiting on #420 and #583 )
- [ ] Change the placement to no longer select a clusterset or change the number of clusters to 0 Ensure the gateway is removed from the spoke cluster
- [ ] Label the gateway with a none existent placement and ensure it is clear what the issue is in the status of control plane

**Comment by R-Lawton** [comment]
For the failed bugs were created for other tests that fix this test to

**Comment by maleck13** [comment]
So the ticked ones failed in this case? Did everything else pass? I kinda expected it the other way round IE ticks for pass and not ticked for failed WDYT?

**Comment by R-Lawton** [comment]
- [ ] Create a ManagedClusterSet resource that selects at least 1 ManagedCluster
- [ ] Bind that ManagedClusterSet to a given namespace
- [ ] Create a placement resource that specifies at least 1 cluster
- [ ] Create a Gateway in the same ns as your placement and label it with `cluster.open-cluster-management.io/placement: [placement name]`
- [ ] Check that the gateway is instantiated on your spoke cluster and the spec and status are as expected
- [ ] Check the hub gateway status reports the gateway as programmed and accepted with no error message
- [ ] Update the Hub Gateway with a new wildcard listener validate spec on spoke updated
- [ ] Update the Hub Gateway with a non wildcard listener validate spec on spoke updated
- [ ] Remove the new listeners from the Gateway in the hub, validate spec on spoke updated
- [ ] Define a HTTPS listener with a secret that doesn't exist, validate that the gateway is no longer in a programmed status state (waiting on #509 )
- [ ] Remove the placement and ensure the gateway is deleted (waiting on #420 and #583 )
- [ ] Change the placement to no longer select a clusterset or change the number of clusters to 0 Ensure the gateway is removed from the spoke cluster
- [ ] Label the gateway with a none existent placement and ensure it is clear what the issue is in the status of control plane
