### ISSUE TITLE
automate tlspolicy manual testing 

### ISSUE THREAD

**Issue by laurafitzgerald** [Kuadrant/multicluster-gateway-controller#587]
All of these steps should be automated - review the existing tests https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/test/integration/tlspolicy_controller_test.go

The steps below are a copy from https://github.com/Kuadrant/multicluster-gateway-controller/issues/507 with any that failed which are covered by bugs listed here marked -> https://github.com/Kuadrant/multicluster-gateway-controller/issues/507#issuecomment-1725504441

- [x] e2e - Setup a gateway definition and label it with the placement label `cluster.open-cluster-management.io/placement: [placement name] `
- [x] integration - Add 3 HTTPS listeners  one wildcard and two non-wildcard and observe the gateway does not get into a programmed state
- [x] integration - Define a TLSPolicy -> Validate it is clear from the TLSPolicy status that the policy has succeeded
- [x] integration - Validate that the gateway is updated with a policyAffected condition - #586
- [x] e2e - Observe the HTTPS secrets are created for any listener and are synced to the cluster
- [ ] e2e - Validate that a wildcard cert was created and a non wildcard (should be able to do this in the browser)
- [ ] e2e - With TLSPolicy in place define some additional HTTPS listeners with named secrets, observe these are also created and synced
- [x] integration - With TLSPolicy in place define a HTTP listener with no TLS and check no secrets created #578 
- [ ] e2e - With TLSPolicy in place delete a HTTPS listener and observe the secrets are cleaned up and the gateway remains available
- [x] integration - With TLSPolicy in place delete a HTTPS Listener -> see relevant certificates re cleaned up
- [ ] e2e - Delete the TLSPolicy and observe only the TLS secrets created by TLSPolicy are removed 
- [x] integration - Delete the TLSPolicy -> see certificate CRs removed
- [x] (the manual one should stay) #585 
- [x] Define an invalid TLSPolicy IE that references a Issuer that doesn't exists, validate that it is clear from the status what the issue is #581
- [x] Define an invalid TLSPolicy IE that references a none existent gateway validate that it is clear from the status what the issue is #361

**Comment by philbrookes** [comment]
>  Setup a gateway definition and label it with the placement label cluster.open-cluster-management.io/placement: [placement name] 
I see why we had this in the manual tests, but I don't think it's necessary in the automated tests, as it's not really testing the TLS Policy but rather OCMs placements. Currently our tests simply create a gateway with the istio gatewayclass, and I think that is probably sufficient?

ping @maleck13 @laurafitzgerald

**Comment by maleck13** [comment]
I think it depends. Part of the functionality is that it sets up the TLS secrets but they then get distributed via manifest work. So if we have the TLSPolicy test only create a policy and check the secrets are created correctly (seems fine) we need to ensure that some other test  is testing placement and ensuring that the secrets get copied to the spokes as expected etc.

**Comment by laurafitzgerald** [comment]
We do some testing that items land on spoke clusters here https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/test/e2e/gateway_single_spoke_test.go#L193 We could add the case there to cover it?

**Comment by philbrookes** [comment]
yeah, it makes sense to me, to have this moved into the e2e tests that have an issuer and the like. I think testing the existence of the secrets makes more sense there too, WDYT @laurafitzgerald ?
